# Solution: https://forum.qubes-os.org/t/trouble-setting-up-apt-cacher-ng/12223
- name: Fix, 403 CONNECT denied error
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list"
    - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list.d/*.list"
  become: true
  failed_when: false

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

