# get(){ gsettings list-recursively | grep dock }


#org.gnome.shell.extensions.dash-to-dock autohide true
- name: Auto-hide the Dock
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/autohide"
    value: "true"
    state: present

#org.gnome.shell.extensions.dash-to-dock autohide-in-fullscreen false
- name: Auto-hide in Fullscreen Dock
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/autohide-in-fullscreen"
    value: "false"
    state: present

#org.gnome.shell.extensions.dash-to-dock multi-monitor true
- name: Show on All displays
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor"
    value: "true"
    state: present


#org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
- name: Position on Screen
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: present
