Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu-Gnome-minimal"

  config.vm.define :beta_vm do |beta_vm|
    beta_vm.vm.provider :libvirt do |v|
      v.memory = 4096
      v.cpus = 6
      v.video_type = 'virtio'
      v.video_accel3d = true
      v.graphics_gl = true
      v.graphics_type = 'spice'
      v.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
      v.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
      #v.graphics_autoport = 'no'
      v.cputopology :sockets => '1', :cores => '3', :threads => '2'
    end
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
