- name: Vagrant client
  hosts: all
  remote_user: vagrant
  roles:
    # - UniInc.AptCacherNg-fix-Vagrant
    # - UniInc.AptCacherNg-Client
    - ansible-role-Ubuntu-Desktop-minimal
    - Gnome-Shell-minimal
